package chat.zekochat.ui.theme

import androidx.compose.ui.graphics.Color

object AppColors {

    val PrimaryLight = Color(0xFF662D91)
    val OnPrimaryLight = Color(0xFFFFFFFD)
    val PrimaryContainerLight = Color(0xFF662D91)
    val OnPrimaryContainerLight = Color(0xFFFFFFFF)
    val SecondaryLight = Color(0xFFFFDE17)
    val OnSecondaryLight = Color(0xFF000000)
    val SecondaryContainerLight = Color(0xFFCBB2E5)
    val OnSecondaryContainerLight = Color(0xFFFFDE17)
    val TertiaryLight = Color(0xFF0060A9)
    val OnTertiaryLight = Color(0xFFFFFFFF)
    val TertiaryContainerLight = Color(0xFFD3E4FF)
    val OnTertiaryContainerLight = Color(0xFF004881)
    val ErrorLight = Color(0xFFC0001F)
    val OnErrorLight = Color(0xFFFFFFFF)
    val ErrorContainerLight = Color(0xFFFFDAD7)
    val OnErrorContainerLight = Color(0xFF410004)
    val BackgroundLight = Color(0xFFF9F9FF)
    val OnBackgroundLight = Color(0xFF161B27)
    val SurfaceLight = Color(0xFFF9F9FF)
    val OnSurfaceLight = Color(0xFF161B27)
    val SurfaceVariantLight = Color(0xFFDCE2F5)
    val OnSurfaceVariantLight = Color(0xFF404756)
    val OutlineLight = Color(0xFF717788)
    val OutlineVariantLight = Color(0xFFC0C6D9)
    val ScrimLight = Color(0xFF000000)
    val InverseSurfaceLight = Color(0xFF2B303D)
    val InverseOnSurfaceLight = Color(0xFFEDF0FF)
    val InversePrimaryLight = Color(0xFFFFB2BA)
    val SurfaceDimLight = Color(0xFFD5D9EA)
    val SurfaceBrightLight = Color(0xFFF9F9FF)
    val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    val SurfaceContainerLowLight = Color(0xFFF1F3FF)
    val SurfaceContainerLight = Color(0xFFE9EDFE)
    val SurfaceContainerHighLight = Color(0xFFE4E8F8)
    val SurfaceContainerHighestLight = Color(0xFFDEE2F2)

    val PrimaryDark = Color(0xFFFFDE17)
    val OnPrimaryDark = Color(0xFF000000)
    val PrimaryContainerDark = Color(0xFF332E36)
    val OnPrimaryContainerDark = Color(0xFFFFDE17)
    val SecondaryDark = Color(0xFF662D91)
    val OnSecondaryDark = Color(0xFFFFFFFD)
    val SecondaryContainerDark = Color(0xFF662D91)
    val OnSecondaryContainerDark = Color(0xFFFFFFFF)
    val TertiaryDark = Color(0xFFA2C9FF)
    val OnTertiaryDark = Color(0xFF00315B)
    val TertiaryContainerDark = Color(0xFF004881)
    val OnTertiaryContainerDark = Color(0xFFD3E4FF)
    val ErrorDark = Color(0xFFFFB3AE)
    val OnErrorDark = Color(0xFF68000C)
    val ErrorContainerDark = Color(0xFF930015)
    val OnErrorContainerDark = Color(0xFFFFDAD7)
    val BackgroundDark = Color(0xFF0E131E)
    val OnBackgroundDark = Color(0xFFDEE2F2)
    val SurfaceDark = Color(0xFF0E131E)
    val OnSurfaceDark = Color(0xFFDEE2F2)
    val SurfaceVariantDark = Color(0xFF404756)
    val OnSurfaceVariantDark = Color(0xFFC0C6D9)
    val OutlineDark = Color(0xFF8A90A2)
    val OutlineVariantDark = Color(0xFF404756)
    val ScrimDark = Color(0xFF000000)
    val InverseSurfaceDark = Color(0xFFDEE2F2)
    val InverseOnSurfaceDark = Color(0xFF2B303D)
    val InversePrimaryDark = Color(0xFFBD0042)
    val SurfaceDimDark = Color(0xFF0E131E)
    val SurfaceBrightDark = Color(0xFF343946)
    val SurfaceContainerLowestDark = Color(0xFF090E19)
    val SurfaceContainerLowDark = Color(0xFF161B27)
    val SurfaceContainerDark = Color(0xFF1A202B)
    val SurfaceContainerHighDark = Color(0xFF252A36)
    val SurfaceContainerHighestDark = Color(0xFF303541)
}